service: api

provider:
  name: aws
  runtime: nodejs6.10
  region: sa-east-1
  environment:
    STATIC_PATH: ${env:STATIC_PATH}

package:
  exclude:
    - "**/*"
    - "!node_modules/**"
    - "!build/backend/Serverless/**"
    - "!build/backend/View/**"
    - "**/*.spec.js"
    - "**/*.spec.js.snap"

functions:
  getHome:
    handler: build/backend/Serverless/home/handler.get
    events:
      - http:
          path: ''
          method: get

  getCategories:
    handler: build/backend/Serverless/home/handler.get
    events:
      - http:
          path: 'categories'
          method: get
  
  authorizerFunc:
    handler: build/backend/Serverless/auth.authorizerFunc