service: api

provider:
  name: aws
  runtime: nodejs6.10
  region: sa-east-1
  environment:
    STATIC_PATH: ${env:STATIC_PATH}

package:
  exclude:
    - "**/*"
    - "!node_modules/**"
    - "!build/backend/Serverless/**"
    - "!build/backend/View/**"
    - "**/*.spec.js"
    - "**/*.spec.js.snap"

functions:
  getUsers:
    handler: build/backend/Serverless/users/handler.get
    events:
      - http:
          path: users
          method: get

  createUsers:
    handler: build/backend/Serverless/users/handler.create
    events:
      - http:
          path: users
          method: post
          authorizer: authorizerFunc
  
  authorizerFunc:
    handler: build/backend/Serverless/auth.authorizerFunc